Repository semuxproject/semux, pull requests merged in 2018-03, with the labels that each got.

#675 Consensus: Improve voting speed
  src/main/java/org/semux/consensus/SemuxBft.java
  src/main/java/org/semux/core/Block.java
  src/main/java/org/semux/core/Transaction.java
  src/main/java/org/semux/crypto/Key.java
  src/test/java/org/semux/consensus/SemuxBftTest.java
  src/test/java/org/semux/core/BlockTest.java
  src/test/java/org/semux/core/TransactionTest.java
Labels: enhancement

#681 Support Customized Base Unit
  config/semux.properties
  src/main/java/org/semux/config/AbstractConfig.java
  src/main/java/org/semux/config/Config.java
  src/main/java/org/semux/core/Unit.java
  src/main/java/org/semux/gui/SemuxGui.java
  src/main/java/org/semux/gui/SwingUtil.java
  src/main/java/org/semux/gui/panel/HomePanel.java
  src/main/java/org/semux/gui/panel/SendPanel.java
  src/test/java/org/semux/gui/SwingUtilTest.java
Labels: feature

#703 GUI,CLI: improve error reporting of ipfilter.json parsing
  src/main/java/org/semux/cli/SemuxCli.java
  src/main/java/org/semux/gui/SemuxGui.java
  src/main/java/org/semux/net/filter/FilterRule.java
  src/main/java/org/semux/net/filter/SemuxIpFilter.java
  src/main/java/org/semux/net/filter/exception/IpFilterJsonParseException.java
  src/test/java/org/semux/net/filter/SemuxIpFilterLoaderTest.java
Labels: enhancement

#717 Refactor Status Bar
  src/main/java/org/semux/consensus/SemuxSync.java
  src/main/java/org/semux/core/SyncManager.java
  src/main/java/org/semux/gui/MainFrame.java
  src/main/java/org/semux/gui/StatusBar.java
  src/main/java/org/semux/gui/SwingUtil.java
  src/main/java/org/semux/gui/panel/HomePanel.java
  src/test/java/org/semux/gui/MainFrameTest.java
  src/test/java/org/semux/gui/SemuxGuiTest.java
  src/test/java/org/semux/gui/StatusBarTest.java
  src/test/java/org/semux/gui/StatusBarTestApplication.java
  src/test/java/org/semux/gui/panel/HomePanelTest.java
  src/test/java/org/semux/gui/panel/HomePanelTestApplication.java
Labels: enhancement

#718 GUI: use BigDecimal instead of double for correctness
  src/main/java/org/semux/gui/SwingUtil.java
  src/test/java/org/semux/gui/SwingUtilTest.java
Labels: enhancement

#726 GUI: Add getBlockByNumber to console
  src/main/java/org/semux/api/ConsoleApi.java
  src/main/java/org/semux/api/ConsoleApiImpl.java
  src/main/java/org/semux/gui/dialog/ConsoleDialog.java
  src/test/java/org/semux/gui/dialog/ConsoleDialogTest.java
Labels: enhancement

#734 Replace Scrutinizer-CI With FindBugs Maven Plugin
  .github/contributing.md
  .scrutinizer.yml
  .travis.yml
  README.md
  pom.xml
  src/main/java/org/semux/Kernel.java
  src/main/java/org/semux/api/SemuxApiImpl.java
  src/main/java/org/semux/cli/SemuxCli.java
  src/main/java/org/semux/gui/MainFrame.java
  src/main/java/org/semux/gui/SemuxGui.java
  src/main/java/org/semux/gui/dialog/AddressBookDialog.java
  src/main/java/org/semux/gui/panel/ReceivePanel.java
  src/main/java/org/semux/gui/panel/TransactionsPanel.java
  src/main/java/org/semux/util/IOUtil.java
  src/main/java/org/semux/util/SystemUtil.java
  src/test/java/org/semux/util/IOUtilTest.java
Labels: enhancement

#742 Consensus: fix sync votes validation issue
  src/main/java/org/semux/consensus/SemuxSync.java
  src/test/java/org/semux/consensus/SemuxSyncTest.java
Labels: bug

#744 Add Splash Screen
  misc/design/splash.bmp
  misc/design/splash.kra
  pom.xml
  src/main/java/org/semux/gui/SemuxEvent.java
  src/main/java/org/semux/gui/SemuxEventListener.java
  src/main/java/org/semux/gui/SemuxGui.java
  src/main/java/org/semux/gui/SplashScreen.java
  src/main/java/org/semux/gui/model/WalletModel.java
  src/main/java/org/semux/wrapper/Wrapper.java
  src/main/resources/org/semux/gui/messages.properties
  src/main/resources/org/semux/gui/splash.png
  src/test/java/org/semux/gui/SplashScreenTest.java
  src/test/java/org/semux/gui/SplashScreenTestApplication.java
  src/test/java/org/semux/windows/Launch4jWrapperIT.java
  src/test/java/org/semux/wrapper/WrapperTest.java
Labels: feature

#625 Initialize a Validator-Activated Softfork UNIFORM_DISTRIBUTION
  appveyor.yml
  pom.xml
  src/main/java/org/semux/Kernel.java
  src/main/java/org/semux/config/AbstractConfig.java
  src/main/java/org/semux/config/Config.java
  src/main/java/org/semux/consensus/SemuxBft.java
  src/main/java/org/semux/consensus/ValidatorActivatedFork.java
  src/main/java/org/semux/core/BlockHeader.java
  src/main/java/org/semux/core/BlockHeaderData.java
  src/main/java/org/semux/core/Blockchain.java
  src/main/java/org/semux/core/BlockchainImpl.java
  src/main/java/org/semux/core/state/DelegateStateImpl.java
  src/main/java/org/semux/db/Db.java
  src/main/java/org/semux/db/DbFactory.java
  src/main/java/org/semux/db/LevelDb.java
  src/main/java/org/semux/db/Migration.java
  src/main/java/org/semux/db/TempDbFactory.java
  src/main/java/org/semux/gui/SemuxGui.java
  src/main/java/org/semux/util/BigIntegerUtil.java
  src/test/java/org/semux/TestUtils.java
  src/test/java/org/semux/api/SemuxApiMock.java
  src/test/java/org/semux/bench/BlockchainPerformance.java
  src/test/java/org/semux/bench/CompressPerformance.java
  src/test/java/org/semux/bench/ValidatorDistributionChart.java
  src/test/java/org/semux/config/MainnetConfigTest.java
  src/test/java/org/semux/consensus/SemuxBftTest.java
  src/test/java/org/semux/core/AmountTest.java
  src/test/java/org/semux/core/BlockHeaderDataTest.java
  src/test/java/org/semux/core/BlockchainImplMigrationTest.java
  src/test/java/org/semux/core/BlockchainImplTest.java
  src/test/java/org/semux/core/ForkSignalSetTest.java
  src/test/java/org/semux/core/PendingManagerTest.java
  src/test/java/org/semux/core/TransactionExecutorTest.java
  src/test/java/org/semux/core/state/AccountStateTest.java
  src/test/java/org/semux/core/state/DelegateStateTest.java
  src/test/java/org/semux/db/LevelDbTest.java
  src/test/java/org/semux/gui/SemuxGuiTest.java
  src/test/java/org/semux/gui/model/WalletDelegateTest.java
  src/test/java/org/semux/gui/model/WalletModelTest.java
  src/test/java/org/semux/gui/panel/DelegatesPanelTest.java
  src/test/java/org/semux/integration/SyncingTest.java
  src/test/java/org/semux/integration/TransactTest.java
  src/test/java/org/semux/integration/UniformDistributionForkSyncingCompatibilityTest.java
  src/test/java/org/semux/log/LoggerConfiguratorTest.java
  src/test/java/org/semux/net/PeerServerMock.java
  src/test/java/org/semux/rules/KernelRule.java
  src/test/java/org/semux/rules/TemporaryDbRule.java
  src/test/java/org/semux/util/BigIntegerUtilTest.java
  src/test/java/org/semux/util/MerkleUtilTest.java
  src/test/resources/config/validators1000.csv
  src/test/resources/database/database-v0.tgz
Labels: enhancement

#749 Docs: move wiki into the main repo to accept PRs on docs
  docs/Block-Rewards.md
  docs/Bug-Bounty-Program.md
  docs/Configurations.md
  docs/Delegates-and-Validators.md
  docs/README.md
  docs/RESTful-API.md
  docs/Semux-BFT-Consensus.md
  docs/Semux-Virtual-Machine.md
  docs/Testnet.md
Labels: docs

#759 DB: separate database from different network
  src/main/java/org/semux/Kernel.java
  src/main/java/org/semux/config/AbstractConfig.java
  src/main/java/org/semux/config/Config.java
Labels: enhancement
